on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
name: Tests
jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl, fileinfo, xdebug, zip #optional
        ini-values: "post_max_size=256M, xdebug.mode=coverage" #optional
    - name: Check PHP Version
      run: php -v
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
            ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install

    - name: Run tests and collect coverage
      run: vendor/bin/phpunit --coverage-clover clover.xml tests
    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: clover.xml
          